Net:
 - 100          # Number of Neurons per Layer
 - "Triplet_STDP"  # Learning Rule
 - True         # Activate Nearest-neighbor (only for pair_STDP)

Behavior:
  - False       # Deactivate Learning Rule for testing model
  - True        # Include monitors for observing the behavior of the network

Train:
  - False       # Deactivate Learning Rule for testing model
  - False       # Include monitors for observing the behavior of the network

Validate:
  - True        # Deactivate Learning Rule for testing model
  - False       # Include monitors for observing the behavior of the network